apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-v2
  namespace: dev
---
apiVersion: v1
kind: Service
metadata:
  name: api-v2
  namespace: dev
spec:
  selector:
    app: api-v2
  ports:
    - port: 9091
      targetPort: 9091
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-v2
  namespace: dev
  labels:
    app: api-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-v2
  template:
    metadata:
      labels:
        app: api-v2
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
    spec:
      containers:
        - name: api
          image: nicholasjackson/fake-service:v0.7.8
          ports:
            - containerPort: 9091
          env:
            - name: 'LISTEN_ADDR'
              value: '127.0.0.1:9091'
            - name: 'NAME'
              value: 'api-v2'
            - name: 'MESSAGE'
              value: 'Response from API v1'
